"""Schema 容量边界。

业务裁剪由 ``AgentConfig`` 和工具处理器负责；本模块中的 hard limit
只用于拦截异常膨胀的模型输出，必须明显高于正常运行配置。
少数 per-call 常量是明确的工具协议限制，用于控制单次外部请求成本。
"""

# 异常保护上限：不应被当作日常业务配置。
STRUCTURED_IDENTIFIER_HARD_LIMIT_CHARS = 512
# 错误文本是旁路诊断,不是载荷;进 checkpoint/DB/事件前钳到可读规模。
RUN_ERROR_TEXT_HARD_LIMIT_CHARS = 2_000
STRUCTURED_TEXT_HARD_LIMIT_CHARS = 16_000
STRUCTURED_SUMMARY_HARD_LIMIT_CHARS = 64_000
STRUCTURED_COLLECTION_HARD_LIMIT = 128
EVIDENCE_REFERENCES_HARD_LIMIT = 256
REPORT_MARKDOWN_HARD_LIMIT_CHARS = 256_000
REPORT_CAVEATS_HARD_LIMIT = 50

# Researcher 单次工具调用协议：限制一次外部操作的扇出，不限制整个方向。
SEARCH_QUERIES_PER_CALL = 2
SOURCE_CANDIDATES_PER_READ = 8
SEARCH_RESULTS_PAGE_HARD_LIMIT = 20
SEARCH_RESULTS_PREVIEW_COUNT = 10
SEARCH_RESULT_SNIPPET_PREVIEW_CHARS = 1_200
# 仅用于 search 客户端审计事件(日志排查用):独立于模型预览数的展示条数,
# 标题按字符截断。二者都不进模型上下文,改这里只影响日志可读性。
SEARCH_RESULTS_AUDIT_PREVIEW_COUNT = 8
SEARCH_RESULT_TITLE_PREVIEW_CHARS = 160
