"""独立服务进程共享的稳定 PostgreSQL 协调键。

advisory lock 的键是全库范围的协调契约：保持具名、唯一、
跨滚动部署稳定。旧进程存活期间改键，会把一段临界区拆成
两把互不相干的锁。
"""

DATABASE_MIGRATION_LOCK_ID = 731_904_620
RUN_CLAIM_CAPACITY_LOCK_ID = 731_904_621
WORKER_STARTUP_RECOVERY_LOCK_ID = 731_904_622
RUN_ADMISSION_LOCK_ID = 731_904_623

POSTGRES_ADVISORY_LOCK_IDS = (
    DATABASE_MIGRATION_LOCK_ID,
    RUN_CLAIM_CAPACITY_LOCK_ID,
    WORKER_STARTUP_RECOVERY_LOCK_ID,
    RUN_ADMISSION_LOCK_ID,
)
