"""Clarifier 交互协议边界。"""

MAX_CLARIFICATION_ROUNDS = 2
CLARIFICATION_QUESTION_MAX_CHARS = 500
CLARIFICATION_OPTION_COUNT = 3
CLARIFICATION_INTENT_MAX_CHARS = 1_000
CLARIFICATION_FOCUS_LIMIT = 4
CLARIFICATION_ASSUMPTION_LIMIT = 3
